spring.application.name=server

# MySQL Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/payment_processing?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Run schema.sql automatically on startup to create tables
spring.sql.init.mode=always
